# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: course_store_db
    environment:
      POSTGRES_DB: course_marketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Remove PGDATA - let PostgreSQL use default location
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d course_marketplace"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped
    networks:
      - course_store_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: course_store_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/course_marketplace
      - SECRET_KEY=course-store-secret-key-change-this-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    restart: unless-stopped
    networks:
      - course_store_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: course_store_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - course_store_network

volumes:
  postgres_data:
    driver: local

networks:
  course_store_network:
    driver: bridge